version: '3.8'

services:

  postgres-customer:
    image: postgres:16-alpine
    container_name: postgres-customer
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - customer-data:/var/lib/postgresql/data

  postgres-account:
    image: postgres:16-alpine
    container_name: postgres-account
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - account-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret
    volumes:
      - rabbit-data:/var/lib/rabbitmq

volumes:
  customer-data:
  account-data:
  rabbit-data: